Notebook to produce raincloud figures. 

```{r}
## setup
Sys.setenv(LANG = "en")
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(patchwork)

if (!require(remotes)) {
    install.packages("remotes")
}
remotes::install_github('jorvlan/raincloudplots')

library(raincloudplots)

```
```{r}

## manually get data
# data_dir <- rstudioapi::selectDirectory()

# some data wranling to get all the parameters together
data_dir <- "~/github/CardioceptionPaper/data"

behavior <- read_csv("~/github/CardioceptionPaper/data/behavior.txt")

bayes_behavior <- read_csv("~/github/CardioceptionPaper/data/bayesianPsychophysic.txt")

behavior <- behavior %>%
  dplyr::select(-matches(c("Threshold", "Slope", "X1"))) %>%
  rename(Condition = Modality) %>%
  filter(Session == "Del1") %>%
  dplyr::select(-matches(c("Session")))
  

 


all_behavior =full_join(behavior, bayes_behavior, by = c("Condition", "Subject"))

all_behavior <- all_behavior %>%
  na.omit(all_behavior) %>%
  filter(X1 != 44)

head(all_behavior)
```

Let's get plotting! 
```{r}
df_1x1 <- data_1x1(
  array_1 = all_behavior$BayesianThreshold[all_behavior$Condition == "Intero"],
  array_2 = all_behavior$BayesianThreshold[all_behavior$Condition == "Extero"],
  jit_distance = .09,
  jit_seed = 321)

raincloud_2 <- raincloud_1x1_repmes(
  data = df_1x1,
  colors = (c('black', 'black')),
  fills = (c('#b22222', '#226ab2')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .8,
  align_clouds = FALSE) +
 
scale_x_continuous(breaks=c(1,2), labels=c("Interoception", "Exteroception"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("Threshold") +
  theme_classic()

raincloud_2


ggsave("threshold_raincloud.png", height = 4, width = 4, dpi = 300)
ggsave("threshold_raincloud.pdf", height = 4, width = 4, dpi = 600)

p1 <- raincloud_2
```

```{r}
df_1x1 <- data_1x1(
  array_1 = all_behavior$BayesianSlope[all_behavior$Condition == "Intero"],
  array_2 = all_behavior$BayesianSlope[all_behavior$Condition == "Extero"],
  jit_distance = .09,
  jit_seed = 321)

raincloud_2 <- raincloud_1x1_repmes(
  data = df_1x1,
  colors = (c('black', 'black')),
  fills = (c('#b22222', '#226ab2')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .85,
  align_clouds = FALSE) +
 
scale_x_continuous(breaks=c(1,2), labels=c("Interoception", "Exteroception"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("Slope") +
  theme_classic()

raincloud_2


ggsave("slope_raincloud.png", height = 4, width = 4, dpi = 300)
ggsave("slope_raincloud.pdf", height = 4, width = 4, dpi = 600)

p2 <- raincloud_2
```
```{r}
p1/p2

ggsave("Fig1_Rainclouds.png", height = 4, width = 4, dpi = 300)

```

SDT - dprime, criterion, RT
```{r}
df_1x1 <- data_1x1(
  array_1 = all_behavior$dPrime[all_behavior$Condition == "Intero"],
  array_2 = all_behavior$dPrime[all_behavior$Condition == "Extero"],
  jit_distance = .09,
  jit_seed = 321)

raincloud_2 <- raincloud_1x1_repmes(
  data = df_1x1,
  colors = (c('black', 'black')),
  fills = (c('#b22222', '#226ab2')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .85,
  align_clouds = FALSE) +
 
scale_x_continuous(breaks=c(1,2), labels=c("Interoception", "Exteroception"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("dPrime") +
  theme_classic()

raincloud_2


ggsave("SDT_dprime_raincloud.png", height = 4, width = 4, dpi = 300)
ggsave("SDT_dprime_raincloud.pdf", height = 4, width = 4, dpi = 600)

p3 <- raincloud_2


```
```{r}
df_1x1 <- data_1x1(
  array_1 = all_behavior$Criterion[all_behavior$Condition == "Intero"],
  array_2 = all_behavior$Criterion[all_behavior$Condition == "Extero"],
  jit_distance = .09,
  jit_seed = 321)

raincloud_2 <- raincloud_1x1_repmes(
  data = df_1x1,
  colors = (c('black', 'black')),
  fills = (c('#b22222', '#226ab2')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .85,
  align_clouds = FALSE) +
 
scale_x_continuous(breaks=c(1,2), labels=c("Interoception", "Exteroception"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("Criterion") +
  theme_classic()

raincloud_2


ggsave("SDT_crit_raincloud.png", height = 4, width = 4, dpi = 300)
ggsave("SDT_crit_raincloud.pdf", height = 4, width = 4, dpi = 600)

p4<- raincloud_2


```

```{r}
df_1x1 <- data_1x1(
  array_1 = all_behavior$DecisionRT[all_behavior$Condition == "Intero"],
  array_2 = all_behavior$DecisionRT[all_behavior$Condition == "Extero"],
  jit_distance = .09,
  jit_seed = 321)

raincloud_2 <- raincloud_1x1_repmes(
  data = df_1x1,
  colors = (c('black', 'black')),
  fills = (c('#b22222', '#226ab2')),
  line_color = 'gray',
  line_alpha = .3,
  size = 1,
  alpha = .85,
  align_clouds = FALSE) +
 
scale_x_continuous(breaks=c(1,2), labels=c("Interoception", "Exteroception"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("RT") +
  theme_classic()

raincloud_2

ggsave("SDT_rt_raincloud.png", height = 4, width = 4, dpi = 300)
ggsave("SDT_rt_raincloud.pdf", height = 4, width = 4, dpi = 600)

p5<- raincloud_2


```

```{r}


patchwork_plot <- (p3 + p4 + p5)
patchwork_plot + plot_annotation(
  title = 'Type-I Performance',
 # subtitle = 'These 3 plots will reveal yet-untold secrets about our beloved data-set',
#  caption = 'Disclaimer: None of these plots are insightful'
)


ggsave("SDT_rainclouds.png", height = 6, width = 12)

```

