
Setup 
```{r}
Sys.setenv(LANG = "en")
library(readr)
library(openvis)
library(dplyr)
library(tidyr)
library(patchwork)

```

```{r}
setwd("C:/Users/Micah Allen/Documents/github/CardioceptionPaper/data")
behavior <- read_csv("behavior.txt", 
    col_types = cols(Modality = col_factor(levels = c("Intero", 
        "Extero"))))

head(behavior)
```
Plots for Del 1

Threshold

```{r}

df <- behavior %>%
  select(-X1) %>%
  select(-HBC) %>%
  filter(Session == "Del2") %>%
  pivot_wider(names_from = "Modality", id_cols = "Subject",
              values_from = c("Accuracy","Confidence", "ConfidenceRT","Criterion",
                              "DecisionRT", "Slope", "Threshold", "dPrime", "TaskDuration"))
df_1x1 <- data_1x1(
  array_1 = df$Threshold_Intero,
  array_2 = df$Threshold_Extero,
  jit_distance = .09,
  jit_seed = 321)


f1 <- raincloud_1x1_repmes(df_1x1, align_clouds = FALSE, alpha = .8)+

  scale_x_continuous(breaks=c(1,2), labels=c("Intero", "Extero"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("Treshold (Δ-BPM)") +
  theme_classic() +
  #ylim(-30,40) +
  scale_color_gradient(low="#b22222", high="#4682b4") +
  scale_fill_gradient(low="#b22222", high="#4682b4") +
  geom_abline(slope = 0, intercept = 0, color = "black")
#scale_color_manual(values=c("#999999", "#E69F00"))

#ggsave("Threshold_RepRainclouds_del2.png", width = 4, height = 4, dpi = 300)

f1
```

Slope

```{r}

df_1x1 <- data_1x1(
  array_1 = df$Slope_Intero,
  array_2 = df$Slope_Extero,
  jit_distance = .09,
  jit_seed = 321)


f2 <- raincloud_1x1_repmes(df_1x1, align_clouds = FALSE, alpha = .8)+

  scale_x_continuous(breaks=c(1,2), labels=c("Intero", "Extero"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("Slope") +
  theme_classic() +
 # ylim(5,20) +
  scale_color_gradient(low="#b22222", high="#4682b4") +
  scale_fill_gradient(low="#b22222", high="#4682b4")
#scale_color_manual(values=c("#999999", "#E69F00"))

#ggsave("Threshold_RepRainclouds_del2.png", width = 4, height = 4, dpi = 300)

f2
```

Combiplot

```{r}

patchwork <- (f1 /f2) 
patchwork + plot_annotation(
  title = 'Psychometric Parameters',
  #subtitle = 'These 3 plots will reveal yet-untold secrets about our beloved data-set',
  #caption = 'Extero'
)


ggsave("Psychometric.png", width = 8, height = 8, dpi = 300)
```

Slope x Session

```{r}

df_1x1 <- data_1x1(
  array_1 = df$Slope_Intero,
  array_2 = df$Slope_Extero,
  jit_distance = .09,
  jit_seed = 321)


figure_1x1_rm <- raincloud_1x1_repmes(df_1x1, align_clouds = FALSE)+

  scale_x_continuous(breaks=c(1,2), labels=c("Intero", "Extero"), limits=c(0, 3)) +
  xlab("Modality") + 
  ylab("Slope") +
  theme_classic() +
 # ylim(5,20) +
  scale_color_gradient(low="#b22222", high="#4682b4") +
  scale_fill_gradient(low="#b22222", high="#4682b4")
#scale_color_manual(values=c("#999999", "#E69F00"))

#ggsave("Slope_RepRainclouds_del2.png", width = 4, height = 4, dpi = 300)

figure_1x1_rm
```

Treshold x Session
```{r}

df3 <- behavior %>%
  select(-X1) %>%
  select(-HBC) %>%
  pivot_wider(names_from = c("Modality", "Session"), id_cols = "Subject",
              values_from = c("Accuracy","Confidence", "ConfidenceRT","Criterion",
                              "DecisionRT", "Slope", "Threshold", "dPrime", "TaskDuration")) %>%
    na.omit()



df_2x2_2.0 <- data_2x2(
  array_1 = df3$Threshold_Intero_Del1,
  array_2 = df3$Threshold_Extero_Del1,
  array_3 = df3$Threshold_Intero_Del2,
  array_4 = df3$Threshold_Extero_Del2,
  label_1 = 'Intero',
  label_2 = 'Extero',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = FALSE)


figure_2x2_2.0 <- raincloud_2x2_repmes(df_2x2_2.0, spread_x_ticks = FALSE) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Time 1", "Time 2"), limits=c(0, 3)) +
  xlab("Session") +
  ylab("Threshold") +
  theme_classic() +
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="bottom", legend.box = "horizontal")
  
#ggsave("Threshold_RepRainclouds_2x2.png", width = 6, height = 4, dpi = 300)

figure_2x2_2.0

```
```{r}


df_2x2_2.0 <- data_2x2(
  array_1 = df3$Slope_Intero_Del1,
  array_2 = df3$Slope_Extero_Del1,
  array_3 = df3$Slope_Intero_Del2,
  array_4 = df3$Slope_Extero_Del2,
  label_1 = 'Intero',
  label_2 = 'Extero',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = FALSE)


figure_2x2_2.0 <- raincloud_2x2_repmes(df_2x2_2.0, spread_x_ticks = FALSE) +
  
  scale_x_continuous(breaks=c(1,2), labels=c("Time 1", "Time 2"), limits=c(0, 3)) +
  xlab("Session") +
  ylab("Slope") +
  theme_classic() +
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="bottom", legend.box = "horizontal")
  
ggsave("Slope_RepRainclouds_2x2.png", width = 6, height = 4, dpi = 300)

figure_2x2_2.0
```

Slope

```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$Slope_Intero_Del1,
  array_2 = df3$Slope_Intero_Del2,
  array_3 = df3$Slope_Extero_Del1,
  array_4 = df3$Slope_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p2 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("Slope") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('B')

p2

```
Threshold
```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$Threshold_Intero_Del1,
  array_2 = df3$Threshold_Intero_Del2,
  array_3 = df3$Threshold_Extero_Del1,
  array_4 = df3$Threshold_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p1 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("Threshold") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')

p1
```
```{r}

patchwork <- (p1 /p2) 
patchwork + plot_annotation(
  title = 'Change in Psychometric Parameters',
  #subtitle = 'These 3 plots will reveal yet-untold secrets about our beloved data-set',
  #caption = 'Extero'
)


ggsave("Overview.png", width = 8, height = 8, dpi = 300)

```

Criterion
```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$Criterion_Intero_Del1,
  array_2 = df3$Criterion_Intero_Del2,
  array_3 = df3$Criterion_Extero_Del1,
  array_4 = df3$Criterion_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p1 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("Criterion") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')+
  geom_abline(slope = 0, intercept = 0, color = "black")

p1
```
Accuracy
```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$Accuracy_Intero_Del1,
  array_2 = df3$Accuracy_Intero_Del2,
  array_3 = df3$Accuracy_Extero_Del1,
  array_4 = df3$Accuracy_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p1 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("Accuracy") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')+
  geom_abline(slope = 0, intercept = 0, color = "black")

p1
```
ConfidenceRT
```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$ConfidenceRT_Intero_Del1,
  array_2 = df3$ConfidenceRT_Intero_Del2,
  array_3 = df3$ConfidenceRT_Extero_Del1,
  array_4 = df3$ConfidenceRT_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p1 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("ConfidenceRT") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')+
  geom_abline(slope = 0, intercept = 0, color = "black")

p1
```

Dprime

```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$dPrime_Intero_Del1,
  array_2 = df3$dPrime_Intero_Del2,
  array_3 = df3$dPrime_Extero_Del1,
  array_4 = df3$dPrime_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p1 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("dPrime") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')

p1
```
Decision RT 
```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$DecisionRT_Intero_Del1,
  array_2 = df3$DecisionRT_Intero_Del2,
  array_3 = df3$DecisionRT_Extero_Del1,
  array_4 = df3$DecisionRT_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p2 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("DecisionRT") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')

p2
```
Confidence
```{r}
df_2x2_1.0 <- data_2x2(
  array_1 = df3$Confidence_Intero_Del1,
  array_2 = df3$Confidence_Intero_Del2,
  array_3 = df3$Confidence_Extero_Del1,
  array_4 = df3$Confidence_Extero_Del2,
  label_1 = 'Del 1',
  label_2 = 'Del 2',
  jit_distance = .05,
  jit_seed = 321,
  spread_x_ticks = TRUE)

p3 <- raincloud_2x2_repmes(df_2x2_1.0, spread_x_ticks = TRUE) +
  
  scale_x_continuous(breaks=c(1,2,3,4),
                     labels=c("InteroDel1", "InteroDel2", "ExteroDel1", "ExteroDel2"),
                     limits=c(0, 5)) +
  xlab("Conditions") +
  ylab("Confidence") +
  theme_classic()+ 
  scale_color_manual(values = c("#4682b4", "#b22222")) +
  scale_fill_manual(values = c("#4682b4", "#b22222")) +
  theme(legend.position="none")+
  ggtitle('A')

p3
```
Combiplot
```{r}

patchwork <- (p1 /p2 /p3) 
patchwork + plot_annotation(
  title = 'Type-I and Type-II Decision Making',
  #subtitle = 'These 3 plots will reveal yet-untold secrets about our beloved data-set',
  #caption = 'Extero'
)


ggsave("Overview.png", width = 8, height = 8, dpi = 300)
```

